[package]
name = "mc_world_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inbt = {path = "../inbt"}
mc_datatypes = {path = "../mc_datatypes"}
thiserror = "1.0.60"
log = "0.4.21"
